server:
  port: 8080

#OpenAPI
springdoc:
  packages-to-scan: no.vegvesen.dia.bifrost.gateway.controllers
  paths-to-match: /**

# org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (56507347) exceeds the configured maximum (10485760)
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
